### ISSUE TITLE
Syntax error near unexpected token `('

### ISSUE THREAD

**Issue by emmahsax** [mojaloop/license-scanner-tool#22]
I got a syntax error running this:
```
$ npm-license-scraper         
/Users/emmasax/.nvm/versions/node/v16.2.0/bin/npm-license-scraper: line 1: syntax error near unexpected token `('
'Users/emmasax/.nvm/versions/node/v16.2.0/bin/npm-license-scraper: line 1: `// Copyright 2019 jackw01. Released under the MIT License (see LICENSE for details).
```

I am running npm version 7.13.0, node v16.2.0, macOS, zsh. I followed the installation instructions in the README. Is there a syntax error, or am I running something wrong?

**Comment by lewisdaly** [comment]
Hey @emmahsax  - I can't find any references to `npm-license-scraper` in this repository (it's been a while since I looked at this repo, so maybe I need to jog my memory...) 

Did you mean this repo: https://www.npmjs.com/package/npm-license-scraper ?

**Comment by emmahsax** [comment]
@lewisdaly I'm so sorry! I made the issue on the wrong GitHub repository! I must've had too many tabs open at once 🤦🏻‍♀️ . Thank you for your help and quick response!

**Comment by lewisdaly** [comment]
No probs @emmahsax  - good luck with your issue :)
